name: 'CI deprecate'
on:
  push:
    branches:
      - '!*'
    tags:
      - '!*'

jobs:
  deprecate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'deprecate'
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm run deprecate
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
